test:
	g++ -std=c++11 test.cpp LinkedList.h -o test
clean-test:
	rm -f test

main:
	g++ -std=c++11 main.cpp LinkedList.h -o main
clean-main:
	rm -f main
debug-main:
	g++ -std=c++11 -g main.cpp LinkedList.h -o main